# Generated by Django 5.0.3 on 2024-03-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('college_email', models.EmailField(max_length=100)),
                ('student_id', models.IntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('isHosteler', models.BooleanField()),
                ('hacker_rank_id', models.CharField(max_length=100)),
                ('isPaid', models.BooleanField(default=False)),
            ],
        ),
    ]
