# Generated by Django 5.0.3 on 2024-03-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_number', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('college_email', models.EmailField(max_length=100)),
                ('student_id', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('isHosteler', models.BooleanField(default=False)),
                ('hacker_rank_id', models.CharField(max_length=100)),
                ('isPaid', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=100)),
                ('isContestOnly', models.BooleanField(default=False)),
                ('day1_att', models.BooleanField(default=False)),
                ('day2_att', models.BooleanField(default=False)),
                ('contest_att', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
