# Generated by Django 5.0.3 on 2024-04-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinators',
            name='unique_code',
            field=models.CharField(default='papa', max_length=100),
        ),
    ]
