# Generated by Django 5.0.3 on 2024-03-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_coordinators'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
