# Generated by Django 5.0.3 on 2024-03-28 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_students_isverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='token',
            field=models.CharField(default=datetime.datetime(2024, 3, 28, 7, 29, 52, 971003, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
